name: ecom_sel
description: "eCommerce Application by Fe"


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

### PACKAGES ###
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # Supabase
  supabase_flutter: ^2.0.0

  ### END OF PACKAGES ###

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  ### LOCAL ASSETS ###
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/icons/brands/

  ### Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic